vim.filetype.add({
  filename = {
    ['dot-zprofile'] = 'zsh',
    ['dot-zshrc'] = 'zsh',
    ['dot-zshenv'] = 'zsh',
    ['dot-zlogin'] = 'zsh',
    ['brewfile'] = 'bash',
    ['dev-deno'] = 'bash',
    ['extract'] = 'bash',
    ['fetch-docs'] = 'python',
    ['fzf-rg'] = 'bash',
    ['git-base'] = 'typescript',
    ['git-detach'] = 'bash',
    ['git-diff-base'] = 'bash',
    ['git-fixup'] = 'bash',
    ['git-prune-local'] = 'bash',
    ['my-ip'] = 'bash',
    ['sbox'] = 'python',
    ['sbox-agent'] = 'bash',
    ['sbox-claude-container'] = 'bash',
    ['sbox-logs'] = 'bash',
    ['stow!'] = 'bash',
    ['tmux-window-finder'] = 'python',
    ['tmux-window-finder-fzf'] = 'sh',
    ['url2har'] = 'python',
    ['utc'] = 'python',
    ['wk'] = 'bash',
  },
})
